---
displayName: ".NET"
description: .NET 2.1 stack with .NET Core SDK and Runtime
tags: [".NET", "C#"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-dotnet.svg
globalMemoryLimit: 2198Mi
