---
displayName: C/C++
description: C and C++ Developer Tools stack
tags: ["c", "c++", "clang", "g++", "make", "cmake"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-cpp.svg
globalMemoryLimit: 1686Mi
