---
displayName: Go
description: Stack with Go 1.11.5
tags: ["Go"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-go.svg
globalMemoryLimit: 1686Mi
