---
displayName: NodeJS MongoDB Web Application
description: Stack with NodeJS 10 and MongoDB 3.4
tags: ["NodeJS", "Express", "MongoDB", "RealWorld", "ubi8", "Centos"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-node.svg?sanitize=true
globalMemoryLimit: 1686Mi
