---
displayName: Java with WildFly Bootable JAR
description: Java stack with OpenJDK 11, Maven 3.6.3 and Bootable JAR
tags: ["RHEL8", "Java", "OpenJDK", "Maven", "EAP", "Microprofile"]
icon: /images/type-jboss.svg
globalMemoryLimit: 3698Mi
