---
displayName: Python
description: Python Stack with Python 3.6
tags: ["Python", "pip"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-python.svg
globalMemoryLimit: 1686Mi
