---
displayName: Java EAP Maven
description: RHEL 8 Java stack with EAP 7.2, OpenJDK 1.8 and Maven 3.5
tags: ["Java", "OpenJDK", "Maven", "EAP"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-jboss.svg
globalMemoryLimit: 2674Mi
