---
displayName: Red Hat Fuse
description: Red Hat Fuse
tags: ["OpenJDK", "Maven", "EAP"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-fuse.svg
globalMemoryLimit: 2816Mi
