---
displayName: Thorntail REST HTTP
description: Quickstart to expose a REST Greeting endpoint using Thorntail
tags: ["Java", "OpenJDK", "Maven", "EAP"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-jboss.svg
globalMemoryLimit: 2674Mi
