---
displayName: NodeJS Express Web Application
description: Stack with NodeJS 10
tags: ["NodeJS", "Express", "ubi8"]
icon: https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/master/ide/codeready-ide-stacks/src/main/resources/stacks-images/type-node.svg?sanitize=true
globalMemoryLimit: 1686Mi
