#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Overall project - PR check - Linelint
# if this fails, see https://github.com/fernandrone/linelint#usage for how to debug the problem locally
on:
  pull_request:
    branches: 
      - '**'
jobs:
  # check EOF newline
  linelint:
    runs-on: ubuntu-20.04
    name: eof-newline
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Linelint
        uses: fernandrone/linelint@0.0.5
        id: linelint
